# Problem 1

In [ ]:
# 1 - numpy kütüphanesini import edin

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin

# 3 - matris'in boyutunu öğrenin

# 4 - matris'i yeniden boyutlandırın

# 5 - matris'in boyut sayısını öğrenin


In [3]:
#1
import numpy as np

#2
x = np.random.randint(0, 10, size=(5))

#3
print(x.shape)

#4
x = x.reshape(5,1)
print(x)

#5
print(x.ndim)

(5,)
[[4]
 [1]
 [2]
 [6]
 [4]]
2


# Problem 2

In [ ]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin

# 2 - Oluşturduğunuz matrisi parçalayın

# 3 - Parçalanmış matrisleri birleştirin


In [4]:
#1
x = np.arange(1, 10, 2)
print(x)

#2
x_1, x_2 = np.split(x, [2])

#3
merged_x = np.concatenate([x_2, x_1])
print(merged_x)






[1 3 5 7 9]
[5 7 9 1 3]


# Problem 3

In [ ]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin

# 2 - matris'in özelliklerini inceleyin


In [19]:
x = np.random.randint(5,100,size=(10,2))
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

2
(10, 2)
20
int64
